let weather = [
    {   day : 'first',
        morning: 123,
        dinner: 234,
        evening: 234,
    },
    {   day : 'second',
        morning: 123,
        dinner: 234,
        evening: 234,
    },
    {   day : 'third',
        morning: 123,
        dinner: 234,
        evening: 234,
    },
    {   day : 'fourth',
        morning: 123,
        dinner: 234,
        evening: 234,
    },
    {   day : 'fifth',
        morning: 123,
        dinner: 234,
        evening: 234,
    },
    {   day : 'sixth',
        morning: 123,
        dinner: 234,
        evening: 234,
    },
    {   day : 'seventh',
        morning: 123,
        dinner: 234,
        evening: 234,
    }
]

console.log(weather);
